---
- name: Define Node Exporter version and platform
  ansible.builtin.set_fact:
    node_exporter_version: "1.8.1"
    node_exporter_platform: "linux-amd64"

- name: Create a dedicated user for Node Exporter
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: yes
    create_home: no

- name: Download and unpack Node Exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform }}/node_exporter"

- name: Copy Node Exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: Create systemd service file for Node Exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Node Exporter

- name: Ensure Node Exporter service is enabled and started
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform }}"
    state: absent

# This handler section is needed for the 'notify' task above.
# Create a file at roles/node_exporter/handlers/main.yml
# and add the content below.
# ---
# - name: Restart Node Exporter
#   ansible.builtin.systemd:
#     name: node_exporter
#     state: restarted