- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install common packages
  ansible.builtin.package:
    name: ['ufw', 'python3-pip']
    state: present