---
# 1. Setup and Install Docker Engine
- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

# 2. Install Docker SDK for Ansible and Start Service
- name: Install Docker SDK for Python
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Ensure Docker service is running and enabled on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

# 3. Run Application Container
- name: Pull and run application container
  community.docker.docker_container:
    name: my-app
    image: "abayomi2/my-simple-app:v6" # 👈 IMPORTANT: Change this!
    state: started
    restart_policy: always
    ports:
      - "8080:8080"

