---
- name: Define Prometheus version and platform
  ansible.builtin.set_fact:
    prometheus_version: "2.53.0"
    prometheus_platform: "linux-amd64"

- name: Create a dedicated user for Prometheus
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false
    system: yes
    create_home: no

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download and unpack Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}/prometheus"

- name: Copy Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}/{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  loop:
    - prometheus
    - promtool

- name: Copy Prometheus console libraries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}/{{ item }}"
    dest: /etc/prometheus/
    remote_src: yes
    owner: prometheus
    group: prometheus
  loop:
    - consoles
    - console_libraries

- name: Create Prometheus configuration file from template
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Create systemd service file for Prometheus
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Prometheus

- name: Ensure Prometheus service is enabled and started
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}"
    state: absent