name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main # This pipeline runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ensure this matches your Terraform region

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      # 👇 MODIFIED STEP: Correctly handle multiline inventory content
      - name: Read Ansible Inventory
        id: inventory
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat ansible/inventory/production.ini >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: . # Run from the root directory

      # This step remains the same
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main-playbook.yml
          directory: ./ansible
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          # Use the content of the file, not the path
          inventory: ${{ steps.inventory.outputs.content }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

